# name: main

# on:
#   push:
#     branches:
#     - '*'
#   pull_request:
#     branches:
#     - master
#     - dev

# jobs:
#   lints:
#     name: Run Lints
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: '14'
#     - run: npm ci
#     - run: npm run bootstrap
#     - run: npm run lint
#     - run: npm run build
#     - run: npm run test-all

