name: Main Workflow
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npx lerna bootstrap
      - run: npm run lint
      - run: npx lerna run build
      - run: npx lerna run test

      # publish
      - run: git config --global user.email "ci@cc.snxdao.io" && git config --global user.name "Synthetix CI"
      - run: git fetch origin ${{ github.head_ref }}
      - run: echo $(git rev-parse --short origin/${{ github.head_ref }})
      # Remove the next line and uncomment the two below to fix dev build issues from inter-package version mismatch issues.
      - run: npx lerna exec npm version 0.0.0-$(git rev-parse --short origin/${{ github.head_ref }})
      # - run: git checkout -b temp
      # - run: npx lerna version 0.0.0-$(git rev-parse --short origin/${{ github.head_ref }}) --exact --no-push -y
      - run: npx lerna exec npm publish -- --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
